/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 52d185789450d6baede61d6710334cd0)
interface __BaseEnv_Env {
	MCP_METRICS: AnalyticsEngineDataset;
	AI_SEARCH: AiSearchNamespace;
	ENVIRONMENT: "staging" | "production" | "development";
	MCP_SERVER_NAME: "Cloudflare Developer Stack MCP Server - Staging" | "Cloudflare Developer Stack MCP Server" | "PLACEHOLDER";
	MCP_SERVER_VERSION: "0.1.0" | "PLACEHOLDER";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/stack-mcp.app");
	}
	interface StagingEnv {
		MCP_METRICS: AnalyticsEngineDataset;
		AI_SEARCH: AiSearchNamespace;
		ENVIRONMENT: "staging";
		MCP_SERVER_NAME: "Cloudflare Developer Stack MCP Server - Staging";
		MCP_SERVER_VERSION: "0.1.0";
	}
	interface ProductionEnv {
		MCP_METRICS: AnalyticsEngineDataset;
		AI_SEARCH: AiSearchNamespace;
		ENVIRONMENT: "production";
		MCP_SERVER_NAME: "Cloudflare Developer Stack MCP Server";
		MCP_SERVER_VERSION: "0.1.0";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
