/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
// Run `pnpm types` to regenerate after changing wrangler.jsonc
interface __BaseEnv_Env {
	MCP_METRICS: AnalyticsEngineDataset;
	ENVIRONMENT: 'development' | 'staging' | 'production';
	MCP_OBJECT: DurableObjectNamespace<import('./src/cloudflare-blog.app').CloudflareBlogMCP>;
	MCP_SERVER_NAME?: string;
	MCP_SERVER_VERSION?: string;
	BLOG_BASE_URL: string;
	SEARCH_BASE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import('./src/cloudflare-blog.app');
		durableNamespaces: 'CloudflareBlogMCP';
	}
	interface StagingEnv {
		MCP_METRICS: AnalyticsEngineDataset;
		ENVIRONMENT: 'staging';
		MCP_OBJECT: DurableObjectNamespace<import('./src/cloudflare-blog.app').CloudflareBlogMCP>;
		BLOG_BASE_URL: string;
		SEARCH_BASE_URL: string;
	}
	interface ProductionEnv {
		MCP_METRICS: AnalyticsEngineDataset;
		ENVIRONMENT: 'production';
		MCP_OBJECT: DurableObjectNamespace<import('./src/cloudflare-blog.app').CloudflareBlogMCP>;
		BLOG_BASE_URL: string;
		SEARCH_BASE_URL: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
