/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 561717d0c91aa890d47efee6a6ebb69a)
interface __BaseEnv_Env {
	MCP_METRICS: AnalyticsEngineDataset;
	ENVIRONMENT: "staging" | "production" | "development";
	MCP_SERVER_NAME: "Cloudflare Blog MCP Server - Staging" | "Cloudflare Blog MCP Server" | "PLACEHOLDER";
	MCP_SERVER_VERSION: "0.1.0" | "PLACEHOLDER";
	BLOG_BASE_URL: "https://blog.cloudflare.com";
	SEARCH_BASE_URL: "https://search.blog.cloudflare.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare-blog.app");
	}
	interface StagingEnv {
		MCP_METRICS: AnalyticsEngineDataset;
		ENVIRONMENT: "staging";
		MCP_SERVER_NAME: "Cloudflare Blog MCP Server - Staging";
		MCP_SERVER_VERSION: "0.1.0";
		BLOG_BASE_URL: "https://blog.cloudflare.com";
		SEARCH_BASE_URL: "https://search.blog.cloudflare.com";
	}
	interface ProductionEnv {
		MCP_METRICS: AnalyticsEngineDataset;
		ENVIRONMENT: "production";
		MCP_SERVER_NAME: "Cloudflare Blog MCP Server";
		MCP_SERVER_VERSION: "0.1.0";
		BLOG_BASE_URL: "https://blog.cloudflare.com";
		SEARCH_BASE_URL: "https://search.blog.cloudflare.com";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
